image: "jupyter/nbviewer"
imagePullPolicy: null

nodeSelector: null

pdbMinAvailable: 2

pdb:
  minAvailable: 1

resources:
  requests:
    memory: 256M
    cpu: "1"

annotations: {}

extraContainers: null
extraVolumes: null
extraVolumeMounts: null

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10

service:
  type: LoadBalancer
  ports:
    nodePort: null

github:
  accessToken: ""
  clientId: ""
  clientSecret: ""

nbviewer:
  baseUrl: "/"
  extraArgs: []
  newrelicIni: ""

memcached:
  AntiAffinity: soft
  replicaCount: 2
  pdbMinAvailable: 1

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

statuspage:
  enabled: false
  image: jupyter/nbviewer-statuspage
  resources: null
  apiKey: ""
  pageId: ""
  metricId: ""

ingress:
  annotations: {}
  host: ''
  secretName: nbviewer-host-secret
  path: /nbviewer
  serviceName: nbviewer
  servicePort: 8888
